id: '17588320940380.9915786481713957'
kind: workflow
name: getUserSettings
nameConfigured: true
steps:
  - id: '17588344585340.1764871481567133'
    type: customSQLQuery
    name: query
    params:
      - type: datasourceId
        value: quickmart_safety_app
        valueType: custom
        mustSelectFirst: true
      - type: query
        value: ./query-query.sql
        valueType: interpolatedValue
        interpolationType: string
      - type: preparedQuery
        value: ./query-preparedQuery.sql
        valueType: interpolatedValue
      - type: preparedQueryParams
        value:
          - __UI_BAKERY__FORMAT_IF_DATE__(params.userId)
        valueType: custom
      - type: customDatabaseName
        value: ''
        valueType: interpolatedValue
      - type: stepVersion
        value: 3
        valueType: custom
      - type: successMapper
        value: ''
        valueType: interpolatedValue
        interpolationType: code
      - type: failureMapper
        value: ''
        valueType: interpolatedValue
        interpolationType: code
      - type: mapperEnabled
        value: false
        valueType: custom
    level: 0
    fallthroughError: false
    isChanged: false
mode: manual
modeConfigured: true
parentPageId: '1'
config:
  shouldConfirm: false
  confirmMessage: Are you sure you'd like to proceed with "{{actions.getUserSettings.name}}"?
  showSuccessToast: false
  successToast: Action "{{actions.getUserSettings.name}}" successfully executed
  successToastDuration: '3000'
  successToastHideByClick: false
  showErrorToast: false
  errorToast: Action "{{actions.getUserSettings.name}}" has failed
  errorToastDuration: '3000'
  errorToastHideByClick: false
  delay: '0'
  runWhenFirstReferenced: true
  preserveStateOnPageChange: false
